services:
  - type: web
    name: driftshield-backend
    runtime: docker
    dockerContext: ./backend/backend
    dockerfilePath: ./backend/backend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        fromDatabase:
          name: driftshield-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://*.onrender.com,https://*.netlify.app,https://*.vercel.app,https://*.github.dev

  - type: web
    name: driftshield-frontend
    runtime: docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: VITE_API_BASE_URL
        value: https://driftshield-backend.onrender.com

 databases:
  - name: driftshield-db
    databaseName: driftshield
    user: driftshield
    plan: free
